# Setup
title:               A portfolio of Ben Cox
tagline:             ''
description:         'A portfolio of some of projects and work by <a href="https://www.linkedin.com/in/benrgcox/" target="_blank">Ben Cox</a>.'
url:                 https://benrgcox.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ben Cox
  url:               https://benrgcox.github.io
  email:             bencox012@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
